spring.application.name=Cycle Step Plugin Example for Java

# Logging configuration
# Log to both console AND file
logging.file.name=${user.home}/AppData/Roaming/Cycle/logs/counting-plugin.log
logging.level.root=INFO
logging.level.io.cyclelabs.stepplugin.example=DEBUG
logging.level.io.cyclelabs.stepplugin=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n